# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigDialog.ui'
#
# Created: Mon Sep 12 20:35:53 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_configDialog(object):
    def setupUi(self, configDialog):
        configDialog.setObjectName(_fromUtf8("configDialog"))
        configDialog.resize(693, 627)
        configDialog.setWindowTitle(QtGui.QApplication.translate("configDialog", "RAFT - Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(configDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.configTab = QtGui.QTabWidget(configDialog)
        self.configTab.setEnabled(True)
        self.configTab.setObjectName(_fromUtf8("configTab"))
        self.configGeneralTab = QtGui.QWidget()
        self.configGeneralTab.setObjectName(_fromUtf8("configGeneralTab"))
        self.groupBox = QtGui.QGroupBox(self.configGeneralTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 328, 141))
        self.groupBox.setTitle(QtGui.QApplication.translate("configDialog", "Network Communication", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bhNetworkBox = QtGui.QCheckBox(self.groupBox)
        self.bhNetworkBox.setToolTip(QtGui.QApplication.translate("configDialog", "Do not make requests to site while rendering captured content", None, QtGui.QApplication.UnicodeUTF8))
        self.bhNetworkBox.setText(QtGui.QApplication.translate("configDialog", "Black Hole Network", None, QtGui.QApplication.UnicodeUTF8))
        self.bhNetworkBox.setChecked(True)
        self.bhNetworkBox.setObjectName(_fromUtf8("bhNetworkBox"))
        self.gridLayout.addWidget(self.bhNetworkBox, 0, 0, 1, 1)
        self.checkBoxUseProxy = QtGui.QCheckBox(self.groupBox)
        self.checkBoxUseProxy.setText(QtGui.QApplication.translate("configDialog", "Use Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseProxy.setObjectName(_fromUtf8("checkBoxUseProxy"))
        self.gridLayout.addWidget(self.checkBoxUseProxy, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("configDialog", "HTTP/HTTPS Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("configDialog", "Proxy Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.confProxyEdit = QtGui.QLineEdit(self.groupBox)
        self.confProxyEdit.setEnabled(False)
        self.confProxyEdit.setToolTip(QtGui.QApplication.translate("configDialog", "Specifying a proxy is not available in this release", None, QtGui.QApplication.UnicodeUTF8))
        self.confProxyEdit.setText(_fromUtf8(""))
        self.confProxyEdit.setPlaceholderText(QtGui.QApplication.translate("configDialog", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.confProxyEdit.setObjectName(_fromUtf8("confProxyEdit"))
        self.gridLayout.addWidget(self.confProxyEdit, 3, 0, 1, 1)
        self.confProxyPort = QtGui.QLineEdit(self.groupBox)
        self.confProxyPort.setEnabled(False)
        self.confProxyPort.setText(_fromUtf8(""))
        self.confProxyPort.setPlaceholderText(QtGui.QApplication.translate("configDialog", "8080", None, QtGui.QApplication.UnicodeUTF8))
        self.confProxyPort.setObjectName(_fromUtf8("confProxyPort"))
        self.gridLayout.addWidget(self.confProxyPort, 3, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.configGeneralTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 331, 251))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("configDialog", "Browser Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.browserAutoLoadImagesCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.browserAutoLoadImagesCheckBox.setGeometry(QtCore.QRect(10, 150, 181, 20))
        self.browserAutoLoadImagesCheckBox.setText(QtGui.QApplication.translate("configDialog", "Auto Load Images?", None, QtGui.QApplication.UnicodeUTF8))
        self.browserAutoLoadImagesCheckBox.setObjectName(_fromUtf8("browserAutoLoadImagesCheckBox"))
        self.browserEnablePluginsCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.browserEnablePluginsCheckBox.setGeometry(QtCore.QRect(10, 90, 191, 20))
        self.browserEnablePluginsCheckBox.setText(QtGui.QApplication.translate("configDialog", "Enable Plugins?", None, QtGui.QApplication.UnicodeUTF8))
        self.browserEnablePluginsCheckBox.setObjectName(_fromUtf8("browserEnablePluginsCheckBox"))
        self.browserEnableJavaCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.browserEnableJavaCheckBox.setGeometry(QtCore.QRect(10, 120, 151, 20))
        self.browserEnableJavaCheckBox.setText(QtGui.QApplication.translate("configDialog", "Enable Java?", None, QtGui.QApplication.UnicodeUTF8))
        self.browserEnableJavaCheckBox.setObjectName(_fromUtf8("browserEnableJavaCheckBox"))
        self.browserEnableWebStorageCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.browserEnableWebStorageCheckBox.setGeometry(QtCore.QRect(10, 60, 181, 20))
        self.browserEnableWebStorageCheckBox.setText(QtGui.QApplication.translate("configDialog", "Enable Web Storage?", None, QtGui.QApplication.UnicodeUTF8))
        self.browserEnableWebStorageCheckBox.setObjectName(_fromUtf8("browserEnableWebStorageCheckBox"))
        self.browserEnableJavaScriptCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.browserEnableJavaScriptCheckBox.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.browserEnableJavaScriptCheckBox.setText(QtGui.QApplication.translate("configDialog", "Enable JavaScript?", None, QtGui.QApplication.UnicodeUTF8))
        self.browserEnableJavaScriptCheckBox.setObjectName(_fromUtf8("browserEnableJavaScriptCheckBox"))
        self.browserUserAgentEdit = QtGui.QLineEdit(self.groupBox_2)
        self.browserUserAgentEdit.setEnabled(False)
        self.browserUserAgentEdit.setGeometry(QtCore.QRect(10, 210, 311, 22))
        self.browserUserAgentEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.browserUserAgentEdit.setText(_fromUtf8(""))
        self.browserUserAgentEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.browserUserAgentEdit.setPlaceholderText(QtGui.QApplication.translate("configDialog", "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_7; en-us) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1", None, QtGui.QApplication.UnicodeUTF8))
        self.browserUserAgentEdit.setObjectName(_fromUtf8("browserUserAgentEdit"))
        self.browserCustomUserAgentCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.browserCustomUserAgentCheckBox.setGeometry(QtCore.QRect(10, 180, 161, 20))
        self.browserCustomUserAgentCheckBox.setText(QtGui.QApplication.translate("configDialog", "Custom User-Agent?", None, QtGui.QApplication.UnicodeUTF8))
        self.browserCustomUserAgentCheckBox.setObjectName(_fromUtf8("browserCustomUserAgentCheckBox"))
        self.configTab.addTab(self.configGeneralTab, _fromUtf8(""))
        self.configCrawlerTab = QtGui.QWidget()
        self.configCrawlerTab.setObjectName(_fromUtf8("configCrawlerTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.configCrawlerTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.spiderConfigGroupBox = QtGui.QGroupBox(self.configCrawlerTab)
        self.spiderConfigGroupBox.setTitle(QtGui.QApplication.translate("configDialog", "Spider", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderConfigGroupBox.setObjectName(_fromUtf8("spiderConfigGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.spiderConfigGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.spiderSubmitFormsCheckBox = QtGui.QCheckBox(self.spiderConfigGroupBox)
        self.spiderSubmitFormsCheckBox.setText(QtGui.QApplication.translate("configDialog", "Submit Forms", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderSubmitFormsCheckBox.setChecked(False)
        self.spiderSubmitFormsCheckBox.setObjectName(_fromUtf8("spiderSubmitFormsCheckBox"))
        self.verticalLayout_3.addWidget(self.spiderSubmitFormsCheckBox)
        self.spiderUseDataBankCheckBox = QtGui.QCheckBox(self.spiderConfigGroupBox)
        self.spiderUseDataBankCheckBox.setText(QtGui.QApplication.translate("configDialog", "Use Data Bank Fill Values", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderUseDataBankCheckBox.setChecked(False)
        self.spiderUseDataBankCheckBox.setObjectName(_fromUtf8("spiderUseDataBankCheckBox"))
        self.verticalLayout_3.addWidget(self.spiderUseDataBankCheckBox)
        self.spiderSubmitUsernamePasswordCheckBox = QtGui.QCheckBox(self.spiderConfigGroupBox)
        self.spiderSubmitUsernamePasswordCheckBox.setText(QtGui.QApplication.translate("configDialog", "Submit Username and Password", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderSubmitUsernamePasswordCheckBox.setChecked(False)
        self.spiderSubmitUsernamePasswordCheckBox.setObjectName(_fromUtf8("spiderSubmitUsernamePasswordCheckBox"))
        self.verticalLayout_3.addWidget(self.spiderSubmitUsernamePasswordCheckBox)
        self.spiderEvaluateJavascriptCheckBox = QtGui.QCheckBox(self.spiderConfigGroupBox)
        self.spiderEvaluateJavascriptCheckBox.setText(QtGui.QApplication.translate("configDialog", "Evaluate JavaScript", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderEvaluateJavascriptCheckBox.setChecked(False)
        self.spiderEvaluateJavascriptCheckBox.setObjectName(_fromUtf8("spiderEvaluateJavascriptCheckBox"))
        self.verticalLayout_3.addWidget(self.spiderEvaluateJavascriptCheckBox)
        self.spiderRetrieveMediaFilesCheckBox = QtGui.QCheckBox(self.spiderConfigGroupBox)
        self.spiderRetrieveMediaFilesCheckBox.setText(QtGui.QApplication.translate("configDialog", "Retrieve Media Files", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderRetrieveMediaFilesCheckBox.setObjectName(_fromUtf8("spiderRetrieveMediaFilesCheckBox"))
        self.verticalLayout_3.addWidget(self.spiderRetrieveMediaFilesCheckBox)
        self.spiderExcludeDangerouPathCheckBox = QtGui.QCheckBox(self.spiderConfigGroupBox)
        self.spiderExcludeDangerouPathCheckBox.setText(QtGui.QApplication.translate("configDialog", "Exclude Dangerous Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderExcludeDangerouPathCheckBox.setObjectName(_fromUtf8("spiderExcludeDangerouPathCheckBox"))
        self.verticalLayout_3.addWidget(self.spiderExcludeDangerouPathCheckBox)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_3.setText(QtGui.QApplication.translate("configDialog", "Max Children:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spiderMaxChildrenEdit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        self.spiderMaxChildrenEdit.setText(_fromUtf8(""))
        self.spiderMaxChildrenEdit.setCursorPosition(0)
        self.spiderMaxChildrenEdit.setObjectName(_fromUtf8("spiderMaxChildrenEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spiderMaxChildrenEdit)
        self.label_4 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_4.setText(QtGui.QApplication.translate("configDialog", "Redundant Content Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_5.setText(QtGui.QApplication.translate("configDialog", "Max Unique Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_6.setText(QtGui.QApplication.translate("configDialog", "Redundant Structure Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_6)
        self.spiderMaxUniqueParametersEdit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        self.spiderMaxUniqueParametersEdit.setText(_fromUtf8(""))
        self.spiderMaxUniqueParametersEdit.setObjectName(_fromUtf8("spiderMaxUniqueParametersEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.spiderMaxUniqueParametersEdit)
        self.spiderRedundantContentLimit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        self.spiderRedundantContentLimit.setText(_fromUtf8(""))
        self.spiderRedundantContentLimit.setObjectName(_fromUtf8("spiderRedundantContentLimit"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.spiderRedundantContentLimit)
        self.spiderRedundantStructureLimit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        self.spiderRedundantStructureLimit.setText(_fromUtf8(""))
        self.spiderRedundantStructureLimit.setObjectName(_fromUtf8("spiderRedundantStructureLimit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.spiderRedundantStructureLimit)
        self.label_7 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_7.setText(QtGui.QApplication.translate("configDialog", "Dangerous Path (Regex):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.spiderDangerousPathEdit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        self.spiderDangerousPathEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spiderDangerousPathEdit.sizePolicy().hasHeightForWidth())
        self.spiderDangerousPathEdit.setSizePolicy(sizePolicy)
        self.spiderDangerousPathEdit.setMinimumSize(QtCore.QSize(360, 0))
        self.spiderDangerousPathEdit.setText(_fromUtf8(""))
        self.spiderDangerousPathEdit.setCursorPosition(0)
        self.spiderDangerousPathEdit.setObjectName(_fromUtf8("spiderDangerousPathEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spiderDangerousPathEdit)
        self.spiderMediaExtensionsEdit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spiderMediaExtensionsEdit.sizePolicy().hasHeightForWidth())
        self.spiderMediaExtensionsEdit.setSizePolicy(sizePolicy)
        self.spiderMediaExtensionsEdit.setMinimumSize(QtCore.QSize(360, 0))
        self.spiderMediaExtensionsEdit.setText(_fromUtf8(""))
        self.spiderMediaExtensionsEdit.setObjectName(_fromUtf8("spiderMediaExtensionsEdit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.spiderMediaExtensionsEdit)
        self.label_8 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_8.setText(QtGui.QApplication.translate("configDialog", "Media Extensions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_9.setText(QtGui.QApplication.translate("configDialog", "Max Links:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.spiderConfigGroupBox)
        self.label_10.setText(QtGui.QApplication.translate("configDialog", "Max Link Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.spiderMaxLinksEdit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        self.spiderMaxLinksEdit.setText(_fromUtf8(""))
        self.spiderMaxLinksEdit.setObjectName(_fromUtf8("spiderMaxLinksEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spiderMaxLinksEdit)
        self.spiderMaxLinkDepthEdit = QtGui.QLineEdit(self.spiderConfigGroupBox)
        self.spiderMaxLinkDepthEdit.setText(_fromUtf8(""))
        self.spiderMaxLinkDepthEdit.setObjectName(_fromUtf8("spiderMaxLinkDepthEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spiderMaxLinkDepthEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.spiderConfigGroupBox)
        self.contentDiscoveryGroupBox = QtGui.QGroupBox(self.configCrawlerTab)
        self.contentDiscoveryGroupBox.setTitle(QtGui.QApplication.translate("configDialog", "Content Discovery", None, QtGui.QApplication.UnicodeUTF8))
        self.contentDiscoveryGroupBox.setObjectName(_fromUtf8("contentDiscoveryGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.contentDiscoveryGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.spiderIterateUserAgentsCheckBox = QtGui.QCheckBox(self.contentDiscoveryGroupBox)
        self.spiderIterateUserAgentsCheckBox.setText(QtGui.QApplication.translate("configDialog", "Iterate User-Agents", None, QtGui.QApplication.UnicodeUTF8))
        self.spiderIterateUserAgentsCheckBox.setChecked(False)
        self.spiderIterateUserAgentsCheckBox.setObjectName(_fromUtf8("spiderIterateUserAgentsCheckBox"))
        self.verticalLayout_4.addWidget(self.spiderIterateUserAgentsCheckBox)
        self.verticalLayout_2.addWidget(self.contentDiscoveryGroupBox)
        self.configTab.addTab(self.configCrawlerTab, _fromUtf8(""))
        self.tabConfigDataBank = QtGui.QWidget()
        self.tabConfigDataBank.setObjectName(_fromUtf8("tabConfigDataBank"))
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.tabConfigDataBank)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.tabDataBank = QtGui.QTabWidget(self.tabConfigDataBank)
        self.tabDataBank.setObjectName(_fromUtf8("tabDataBank"))
        self.tabDataBankFormFill = QtGui.QWidget()
        self.tabDataBankFormFill.setObjectName(_fromUtf8("tabDataBankFormFill"))
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.tabDataBankFormFill)
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.tabWidgetDataBankFormFill = QtGui.QTabWidget(self.tabDataBankFormFill)
        self.tabWidgetDataBankFormFill.setObjectName(_fromUtf8("tabWidgetDataBankFormFill"))
        self.tabDataBankFormFillValues = QtGui.QWidget()
        self.tabDataBankFormFillValues.setObjectName(_fromUtf8("tabDataBankFormFillValues"))
        self.gridLayout1 = QtGui.QGridLayout(self.tabDataBankFormFillValues)
        self.gridLayout1.setObjectName(_fromUtf8("gridLayout1"))
        self.frame_8 = QtGui.QFrame(self.tabDataBankFormFillValues)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.formLayout_4 = QtGui.QFormLayout(self.frame_8)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_21 = QtGui.QLabel(self.frame_8)
        self.label_21.setText(QtGui.QApplication.translate("configDialog", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.formFillFirstNameEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillFirstNameEdit.setObjectName(_fromUtf8("formFillFirstNameEdit"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.formFillFirstNameEdit)
        self.label_22 = QtGui.QLabel(self.frame_8)
        self.label_22.setText(QtGui.QApplication.translate("configDialog", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.formFillLastNameEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillLastNameEdit.setObjectName(_fromUtf8("formFillLastNameEdit"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.formFillLastNameEdit)
        self.label_23 = QtGui.QLabel(self.frame_8)
        self.label_23.setText(QtGui.QApplication.translate("configDialog", "Email Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.formFillEmailAddressEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillEmailAddressEdit.setObjectName(_fromUtf8("formFillEmailAddressEdit"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.formFillEmailAddressEdit)
        self.label_24 = QtGui.QLabel(self.frame_8)
        self.label_24.setText(QtGui.QApplication.translate("configDialog", "Company", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_24)
        self.formFillCompanyEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillCompanyEdit.setObjectName(_fromUtf8("formFillCompanyEdit"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.formFillCompanyEdit)
        self.label_25 = QtGui.QLabel(self.frame_8)
        self.label_25.setText(QtGui.QApplication.translate("configDialog", "Address 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_25)
        self.formFillAddress1Edit = QtGui.QLineEdit(self.frame_8)
        self.formFillAddress1Edit.setObjectName(_fromUtf8("formFillAddress1Edit"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.formFillAddress1Edit)
        self.label_26 = QtGui.QLabel(self.frame_8)
        self.label_26.setText(QtGui.QApplication.translate("configDialog", "Address 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_26)
        self.formFillAddress2Edit = QtGui.QLineEdit(self.frame_8)
        self.formFillAddress2Edit.setObjectName(_fromUtf8("formFillAddress2Edit"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.formFillAddress2Edit)
        self.label_27 = QtGui.QLabel(self.frame_8)
        self.label_27.setText(QtGui.QApplication.translate("configDialog", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_27)
        self.formFillCityEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillCityEdit.setObjectName(_fromUtf8("formFillCityEdit"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.formFillCityEdit)
        self.label_28 = QtGui.QLabel(self.frame_8)
        self.label_28.setText(QtGui.QApplication.translate("configDialog", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_28)
        self.formFillStateEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillStateEdit.setObjectName(_fromUtf8("formFillStateEdit"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.formFillStateEdit)
        self.label_29 = QtGui.QLabel(self.frame_8)
        self.label_29.setText(QtGui.QApplication.translate("configDialog", "Zip Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_29)
        self.formFillZipCodeEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillZipCodeEdit.setObjectName(_fromUtf8("formFillZipCodeEdit"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.FieldRole, self.formFillZipCodeEdit)
        self.label_30 = QtGui.QLabel(self.frame_8)
        self.label_30.setText(QtGui.QApplication.translate("configDialog", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_4.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_30)
        self.formFillCountryEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillCountryEdit.setObjectName(_fromUtf8("formFillCountryEdit"))
        self.formLayout_4.setWidget(9, QtGui.QFormLayout.FieldRole, self.formFillCountryEdit)
        self.label_31 = QtGui.QLabel(self.frame_8)
        self.label_31.setText(QtGui.QApplication.translate("configDialog", "Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_4.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_31)
        self.formFillPhoneEdit = QtGui.QLineEdit(self.frame_8)
        self.formFillPhoneEdit.setObjectName(_fromUtf8("formFillPhoneEdit"))
        self.formLayout_4.setWidget(10, QtGui.QFormLayout.FieldRole, self.formFillPhoneEdit)
        self.gridLayout1.addWidget(self.frame_8, 0, 0, 1, 1)
        self.frame_9 = QtGui.QFrame(self.tabDataBankFormFillValues)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.formLayout_5 = QtGui.QFormLayout(self.frame_9)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_32 = QtGui.QLabel(self.frame_9)
        self.label_32.setText(QtGui.QApplication.translate("configDialog", "SSN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_32)
        self.formFillSSNEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillSSNEdit.setObjectName(_fromUtf8("formFillSSNEdit"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.formFillSSNEdit)
        self.label_33 = QtGui.QLabel(self.frame_9)
        self.label_33.setText(QtGui.QApplication.translate("configDialog", "Birth Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_33)
        self.formFillBirthDateEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillBirthDateEdit.setObjectName(_fromUtf8("formFillBirthDateEdit"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.formFillBirthDateEdit)
        self.label_34 = QtGui.QLabel(self.frame_9)
        self.label_34.setText(QtGui.QApplication.translate("configDialog", "Passport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_34)
        self.formFillPassportEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillPassportEdit.setObjectName(_fromUtf8("formFillPassportEdit"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.formFillPassportEdit)
        self.label_35 = QtGui.QLabel(self.frame_9)
        self.label_35.setText(QtGui.QApplication.translate("configDialog", "Credit Card", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_35)
        self.formFillCreditCardEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillCreditCardEdit.setObjectName(_fromUtf8("formFillCreditCardEdit"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.formFillCreditCardEdit)
        self.label_36 = QtGui.QLabel(self.frame_9)
        self.label_36.setText(QtGui.QApplication.translate("configDialog", "Postal Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_36)
        self.formFillPostalCodeEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillPostalCodeEdit.setObjectName(_fromUtf8("formFillPostalCodeEdit"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.formFillPostalCodeEdit)
        self.label_37 = QtGui.QLabel(self.frame_9)
        self.label_37.setText(QtGui.QApplication.translate("configDialog", "ID Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_37)
        self.formFillIDNumberEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillIDNumberEdit.setObjectName(_fromUtf8("formFillIDNumberEdit"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.formFillIDNumberEdit)
        self.label_38 = QtGui.QLabel(self.frame_9)
        self.label_38.setText(QtGui.QApplication.translate("configDialog", "Home Page URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_38)
        self.formFillHomePageUrlEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillHomePageUrlEdit.setObjectName(_fromUtf8("formFillHomePageUrlEdit"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.FieldRole, self.formFillHomePageUrlEdit)
        self.label_39 = QtGui.QLabel(self.frame_9)
        self.label_39.setText(QtGui.QApplication.translate("configDialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_39)
        self.formFillUsernameEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillUsernameEdit.setObjectName(_fromUtf8("formFillUsernameEdit"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.FieldRole, self.formFillUsernameEdit)
        self.label_40 = QtGui.QLabel(self.frame_9)
        self.label_40.setText(QtGui.QApplication.translate("configDialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_40)
        self.formFillPasswordEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillPasswordEdit.setObjectName(_fromUtf8("formFillPasswordEdit"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.FieldRole, self.formFillPasswordEdit)
        self.label_41 = QtGui.QLabel(self.frame_9)
        self.label_41.setText(QtGui.QApplication.translate("configDialog", "Unknown Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_41)
        self.formFillUnknownTextEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillUnknownTextEdit.setObjectName(_fromUtf8("formFillUnknownTextEdit"))
        self.formLayout_5.setWidget(9, QtGui.QFormLayout.FieldRole, self.formFillUnknownTextEdit)
        self.label_42 = QtGui.QLabel(self.frame_9)
        self.label_42.setText(QtGui.QApplication.translate("configDialog", "Unknown Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_42)
        self.formFillUnknownNumberEdit = QtGui.QLineEdit(self.frame_9)
        self.formFillUnknownNumberEdit.setObjectName(_fromUtf8("formFillUnknownNumberEdit"))
        self.formLayout_5.setWidget(10, QtGui.QFormLayout.FieldRole, self.formFillUnknownNumberEdit)
        self.gridLayout1.addWidget(self.frame_9, 0, 1, 1, 1)
        self.tabWidgetDataBankFormFill.addTab(self.tabDataBankFormFillValues, _fromUtf8(""))
        self.tabDataBankFormFillPatterns = QtGui.QWidget()
        self.tabDataBankFormFillPatterns.setObjectName(_fromUtf8("tabDataBankFormFillPatterns"))
        self.gridLayout_fillpatterns = QtGui.QGridLayout(self.tabDataBankFormFillPatterns)
        self.gridLayout_fillpatterns.setObjectName(_fromUtf8("gridLayout_fillpatterns"))
        self.frame_8_fillpatterns = QtGui.QFrame(self.tabDataBankFormFillPatterns)
        self.frame_8_fillpatterns.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8_fillpatterns.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8_fillpatterns.setObjectName(_fromUtf8("frame_8_fillpatterns"))
        self.formLayout_4_fillpatterns = QtGui.QFormLayout(self.frame_8_fillpatterns)
        self.formLayout_4_fillpatterns.setObjectName(_fromUtf8("formLayout_4_fillpatterns"))
        self.label_fillpatterns_21 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_21.setText(QtGui.QApplication.translate("configDialog", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_21.setObjectName(_fromUtf8("label_fillpatterns_21"))
        self.formLayout_4_fillpatterns.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_21)
        self.formFillFirstNamePattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillFirstNamePattern.setObjectName(_fromUtf8("formFillFirstNamePattern"))
        self.formLayout_4_fillpatterns.setWidget(0, QtGui.QFormLayout.FieldRole, self.formFillFirstNamePattern)
        self.label_fillpatterns_22 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_22.setText(QtGui.QApplication.translate("configDialog", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_22.setObjectName(_fromUtf8("label_fillpatterns_22"))
        self.formLayout_4_fillpatterns.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_22)
        self.formFillLastNamePattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillLastNamePattern.setObjectName(_fromUtf8("formFillLastNamePattern"))
        self.formLayout_4_fillpatterns.setWidget(1, QtGui.QFormLayout.FieldRole, self.formFillLastNamePattern)
        self.label_fillpatterns_23 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_23.setText(QtGui.QApplication.translate("configDialog", "Email Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_23.setObjectName(_fromUtf8("label_fillpatterns_23"))
        self.formLayout_4_fillpatterns.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_23)
        self.formFillEmailAddressPattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillEmailAddressPattern.setObjectName(_fromUtf8("formFillEmailAddressPattern"))
        self.formLayout_4_fillpatterns.setWidget(2, QtGui.QFormLayout.FieldRole, self.formFillEmailAddressPattern)
        self.label_fillpatterns_24 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_24.setText(QtGui.QApplication.translate("configDialog", "Company", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_24.setObjectName(_fromUtf8("label_fillpatterns_24"))
        self.formLayout_4_fillpatterns.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_24)
        self.formFillCompanyPattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillCompanyPattern.setObjectName(_fromUtf8("formFillCompanyPattern"))
        self.formLayout_4_fillpatterns.setWidget(3, QtGui.QFormLayout.FieldRole, self.formFillCompanyPattern)
        self.label_fillpatterns_25 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_25.setText(QtGui.QApplication.translate("configDialog", "Address 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_25.setObjectName(_fromUtf8("label_fillpatterns_25"))
        self.formLayout_4_fillpatterns.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_25)
        self.formFillAddress1Pattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillAddress1Pattern.setObjectName(_fromUtf8("formFillAddress1Pattern"))
        self.formLayout_4_fillpatterns.setWidget(4, QtGui.QFormLayout.FieldRole, self.formFillAddress1Pattern)
        self.label_fillpatterns_26 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_26.setText(QtGui.QApplication.translate("configDialog", "Address 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_26.setObjectName(_fromUtf8("label_fillpatterns_26"))
        self.formLayout_4_fillpatterns.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_26)
        self.formFillAddress2Pattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillAddress2Pattern.setObjectName(_fromUtf8("formFillAddress2Pattern"))
        self.formLayout_4_fillpatterns.setWidget(5, QtGui.QFormLayout.FieldRole, self.formFillAddress2Pattern)
        self.label_fillpatterns_27 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_27.setText(QtGui.QApplication.translate("configDialog", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_27.setObjectName(_fromUtf8("label_fillpatterns_27"))
        self.formLayout_4_fillpatterns.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_27)
        self.formFillCityPattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillCityPattern.setObjectName(_fromUtf8("formFillCityPattern"))
        self.formLayout_4_fillpatterns.setWidget(6, QtGui.QFormLayout.FieldRole, self.formFillCityPattern)
        self.label_fillpatterns_28 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_28.setText(QtGui.QApplication.translate("configDialog", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_28.setObjectName(_fromUtf8("label_fillpatterns_28"))
        self.formLayout_4_fillpatterns.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_28)
        self.formFillStatePattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillStatePattern.setObjectName(_fromUtf8("formFillStatePattern"))
        self.formLayout_4_fillpatterns.setWidget(7, QtGui.QFormLayout.FieldRole, self.formFillStatePattern)
        self.label_fillpatterns_29 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_29.setText(QtGui.QApplication.translate("configDialog", "Zip Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_29.setObjectName(_fromUtf8("label_fillpatterns_29"))
        self.formLayout_4_fillpatterns.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_29)
        self.formFillZipCodePattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillZipCodePattern.setObjectName(_fromUtf8("formFillZipCodePattern"))
        self.formLayout_4_fillpatterns.setWidget(8, QtGui.QFormLayout.FieldRole, self.formFillZipCodePattern)
        self.label_fillpatterns_30 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_30.setText(QtGui.QApplication.translate("configDialog", "Country", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_30.setObjectName(_fromUtf8("label_fillpatterns_30"))
        self.formLayout_4_fillpatterns.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_30)
        self.formFillCountryPattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillCountryPattern.setObjectName(_fromUtf8("formFillCountryPattern"))
        self.formLayout_4_fillpatterns.setWidget(9, QtGui.QFormLayout.FieldRole, self.formFillCountryPattern)
        self.label_fillpatterns_31 = QtGui.QLabel(self.frame_8_fillpatterns)
        self.label_fillpatterns_31.setText(QtGui.QApplication.translate("configDialog", "Phone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_31.setObjectName(_fromUtf8("label_fillpatterns_31"))
        self.formLayout_4_fillpatterns.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_31)
        self.formFillPhonePattern = QtGui.QLineEdit(self.frame_8_fillpatterns)
        self.formFillPhonePattern.setObjectName(_fromUtf8("formFillPhonePattern"))
        self.formLayout_4_fillpatterns.setWidget(10, QtGui.QFormLayout.FieldRole, self.formFillPhonePattern)
        self.gridLayout_fillpatterns.addWidget(self.frame_8_fillpatterns, 0, 0, 1, 1)
        self.frame_91 = QtGui.QFrame(self.tabDataBankFormFillPatterns)
        self.frame_91.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_91.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_91.setObjectName(_fromUtf8("frame_91"))
        self.formLayout_5_fillpatterns = QtGui.QFormLayout(self.frame_91)
        self.formLayout_5_fillpatterns.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5_fillpatterns.setObjectName(_fromUtf8("formLayout_5_fillpatterns"))
        self.label_fillpatterns_32 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_32.setText(QtGui.QApplication.translate("configDialog", "SSN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_32.setObjectName(_fromUtf8("label_fillpatterns_32"))
        self.formLayout_5_fillpatterns.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_32)
        self.formFillSSNPattern = QtGui.QLineEdit(self.frame_91)
        self.formFillSSNPattern.setObjectName(_fromUtf8("formFillSSNPattern"))
        self.formLayout_5_fillpatterns.setWidget(0, QtGui.QFormLayout.FieldRole, self.formFillSSNPattern)
        self.label_fillpatterns_33 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_33.setText(QtGui.QApplication.translate("configDialog", "Birth Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_33.setObjectName(_fromUtf8("label_fillpatterns_33"))
        self.formLayout_5_fillpatterns.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_33)
        self.formFillBirthDatePattern = QtGui.QLineEdit(self.frame_91)
        self.formFillBirthDatePattern.setObjectName(_fromUtf8("formFillBirthDatePattern"))
        self.formLayout_5_fillpatterns.setWidget(1, QtGui.QFormLayout.FieldRole, self.formFillBirthDatePattern)
        self.label_fillpatterns_34 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_34.setText(QtGui.QApplication.translate("configDialog", "Passport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_34.setObjectName(_fromUtf8("label_fillpatterns_34"))
        self.formLayout_5_fillpatterns.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_34)
        self.formFillPassportPattern = QtGui.QLineEdit(self.frame_91)
        self.formFillPassportPattern.setObjectName(_fromUtf8("formFillPassportPattern"))
        self.formLayout_5_fillpatterns.setWidget(2, QtGui.QFormLayout.FieldRole, self.formFillPassportPattern)
        self.label_fillpatterns_35 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_35.setText(QtGui.QApplication.translate("configDialog", "Credit Card", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_35.setObjectName(_fromUtf8("label_fillpatterns_35"))
        self.formLayout_5_fillpatterns.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_35)
        self.formFillCreditCardPattern = QtGui.QLineEdit(self.frame_91)
        self.formFillCreditCardPattern.setObjectName(_fromUtf8("formFillCreditCardPattern"))
        self.formLayout_5_fillpatterns.setWidget(3, QtGui.QFormLayout.FieldRole, self.formFillCreditCardPattern)
        self.label_fillpatterns_36 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_36.setText(QtGui.QApplication.translate("configDialog", "Postal Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_36.setObjectName(_fromUtf8("label_fillpatterns_36"))
        self.formLayout_5_fillpatterns.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_36)
        self.formFillPostalCodePattern = QtGui.QLineEdit(self.frame_91)
        self.formFillPostalCodePattern.setObjectName(_fromUtf8("formFillPostalCodePattern"))
        self.formLayout_5_fillpatterns.setWidget(4, QtGui.QFormLayout.FieldRole, self.formFillPostalCodePattern)
        self.label_fillpatterns_37 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_37.setText(QtGui.QApplication.translate("configDialog", "ID Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_37.setObjectName(_fromUtf8("label_fillpatterns_37"))
        self.formLayout_5_fillpatterns.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_37)
        self.formFillIDNumberPattern = QtGui.QLineEdit(self.frame_91)
        self.formFillIDNumberPattern.setObjectName(_fromUtf8("formFillIDNumberPattern"))
        self.formLayout_5_fillpatterns.setWidget(5, QtGui.QFormLayout.FieldRole, self.formFillIDNumberPattern)
        self.label_fillpatterns_38 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_38.setText(QtGui.QApplication.translate("configDialog", "Home Page URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_38.setObjectName(_fromUtf8("label_fillpatterns_38"))
        self.formLayout_5_fillpatterns.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_38)
        self.formFillHomePageUrlPattern = QtGui.QLineEdit(self.frame_91)
        self.formFillHomePageUrlPattern.setObjectName(_fromUtf8("formFillHomePageUrlPattern"))
        self.formLayout_5_fillpatterns.setWidget(6, QtGui.QFormLayout.FieldRole, self.formFillHomePageUrlPattern)
        self.label_fillpatterns_39 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_39.setText(QtGui.QApplication.translate("configDialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_39.setObjectName(_fromUtf8("label_fillpatterns_39"))
        self.formLayout_5_fillpatterns.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_39)
        self.formFillUsernamePattern = QtGui.QLineEdit(self.frame_91)
        self.formFillUsernamePattern.setObjectName(_fromUtf8("formFillUsernamePattern"))
        self.formLayout_5_fillpatterns.setWidget(7, QtGui.QFormLayout.FieldRole, self.formFillUsernamePattern)
        self.label_fillpatterns_40 = QtGui.QLabel(self.frame_91)
        self.label_fillpatterns_40.setText(QtGui.QApplication.translate("configDialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fillpatterns_40.setObjectName(_fromUtf8("label_fillpatterns_40"))
        self.formLayout_5_fillpatterns.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_fillpatterns_40)
        self.formFillPasswordPattern = QtGui.QLineEdit(self.frame_91)
        self.formFillPasswordPattern.setObjectName(_fromUtf8("formFillPasswordPattern"))
        self.formLayout_5_fillpatterns.setWidget(8, QtGui.QFormLayout.FieldRole, self.formFillPasswordPattern)
        self.label_43 = QtGui.QLabel(self.frame_91)
        self.label_43.setText(QtGui.QApplication.translate("configDialog", "Full Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.formLayout_5_fillpatterns.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_43)
        self.formFillFullNamePattern = QtGui.QLineEdit(self.frame_91)
        self.formFillFullNamePattern.setObjectName(_fromUtf8("formFillFullNamePattern"))
        self.formLayout_5_fillpatterns.setWidget(9, QtGui.QFormLayout.FieldRole, self.formFillFullNamePattern)
        self.gridLayout_fillpatterns.addWidget(self.frame_91, 0, 1, 1, 1)
        self.tabWidgetDataBankFormFill.addTab(self.tabDataBankFormFillPatterns, _fromUtf8(""))
        self.verticalLayout_34.addWidget(self.tabWidgetDataBankFormFill)
        self.tabDataBank.addTab(self.tabDataBankFormFill, _fromUtf8(""))
        self.tabDataBankDataLists = QtGui.QWidget()
        self.tabDataBankDataLists.setObjectName(_fromUtf8("tabDataBankDataLists"))
        self.tabDataBank.addTab(self.tabDataBankDataLists, _fromUtf8(""))
        self.tabDataBankFuzzPayloads = QtGui.QWidget()
        self.tabDataBankFuzzPayloads.setObjectName(_fromUtf8("tabDataBankFuzzPayloads"))
        self.verticalLayout_61 = QtGui.QVBoxLayout(self.tabDataBankFuzzPayloads)
        self.verticalLayout_61.setObjectName(_fromUtf8("verticalLayout_61"))
        self.splitter_14 = QtGui.QSplitter(self.tabDataBankFuzzPayloads)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName(_fromUtf8("splitter_14"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter_14)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_60 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_60.setMargin(0)
        self.verticalLayout_60.setObjectName(_fromUtf8("verticalLayout_60"))
        self.dbankPayloadsBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.dbankPayloadsBox.setObjectName(_fromUtf8("dbankPayloadsBox"))
        self.verticalLayout_60.addWidget(self.dbankPayloadsBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_60.addItem(spacerItem)
        self.dbankFuzzValuesEdit = QtGui.QPlainTextEdit(self.splitter_14)
        self.dbankFuzzValuesEdit.setReadOnly(True)
        self.dbankFuzzValuesEdit.setObjectName(_fromUtf8("dbankFuzzValuesEdit"))
        self.verticalLayout_61.addWidget(self.splitter_14)
        self.tabDataBank.addTab(self.tabDataBankFuzzPayloads, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabDataBank.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_33.addWidget(self.tabDataBank)
        self.configTab.addTab(self.tabConfigDataBank, _fromUtf8(""))
        self.verticalLayout.addWidget(self.configTab)
        self.buttonBox = QtGui.QDialogButtonBox(configDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(configDialog)
        self.configTab.setCurrentIndex(0)
        self.tabDataBank.setCurrentIndex(0)
        self.tabWidgetDataBankFormFill.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), configDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), configDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(configDialog)

    def retranslateUi(self, configDialog):
        self.configTab.setTabText(self.configTab.indexOf(self.configGeneralTab), QtGui.QApplication.translate("configDialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.configTab.setTabText(self.configTab.indexOf(self.configCrawlerTab), QtGui.QApplication.translate("configDialog", "Crawler", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetDataBankFormFill.setTabText(self.tabWidgetDataBankFormFill.indexOf(self.tabDataBankFormFillValues), QtGui.QApplication.translate("configDialog", "Fill Values", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetDataBankFormFill.setTabText(self.tabWidgetDataBankFormFill.indexOf(self.tabDataBankFormFillPatterns), QtGui.QApplication.translate("configDialog", "Fill Patterns", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDataBank.setTabText(self.tabDataBank.indexOf(self.tabDataBankFormFill), QtGui.QApplication.translate("configDialog", "Form Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDataBank.setTabText(self.tabDataBank.indexOf(self.tabDataBankDataLists), QtGui.QApplication.translate("configDialog", "Data Lists", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDataBank.setTabText(self.tabDataBank.indexOf(self.tabDataBankFuzzPayloads), QtGui.QApplication.translate("configDialog", "Fuzz Payloads", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDataBank.setTabText(self.tabDataBank.indexOf(self.tab_5), QtGui.QApplication.translate("configDialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.configTab.setTabText(self.configTab.indexOf(self.tabConfigDataBank), QtGui.QApplication.translate("configDialog", "Data Bank", None, QtGui.QApplication.UnicodeUTF8))

