# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DbViewer.ui'
#
# Created: Sun Oct  3 13:17:30 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(-1)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.createButton = QtGui.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/New-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createButton.setIcon(icon)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout_6.addWidget(self.createButton)
        self.openButton = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/Open-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon1)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_6.addWidget(self.openButton)
        self.zoomInButton = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/Zoom-In-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomInButton.setIcon(icon2)
        self.zoomInButton.setObjectName("zoomInButton")
        self.horizontalLayout_6.addWidget(self.zoomInButton)
        self.zoomOutButton = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/Zoom-Out-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomOutButton.setIcon(icon3)
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.horizontalLayout_6.addWidget(self.zoomOutButton)
        self.diffButton = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/diff-icon-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.diffButton.setIcon(icon4)
        self.diffButton.setObjectName("diffButton")
        self.horizontalLayout_6.addWidget(self.diffButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.dataTree = QtGui.QTreeWidget(self.splitter_2)
        self.dataTree.setAlternatingRowColors(True)
        self.dataTree.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.dataTree.setItemsExpandable(True)
        self.dataTree.setColumnCount(7)
        self.dataTree.setObjectName("dataTree")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.viewTab = QtGui.QTabWidget(self.splitter)
        self.viewTab.setObjectName("viewTab")
        self.rawTab = QtGui.QWidget()
        self.rawTab.setObjectName("rawTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.rawTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reqEdit = QtGui.QPlainTextEdit(self.rawTab)
        self.reqEdit.setObjectName("reqEdit")
        self.verticalLayout_2.addWidget(self.reqEdit)
        self.viewTab.addTab(self.rawTab, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rawRespEdit = Qsci.QsciScintilla(self.tab)
        self.rawRespEdit.setToolTip("")
        self.rawRespEdit.setWhatsThis("")
        self.rawRespEdit.setObjectName("rawRespEdit")
        self.verticalLayout_4.addWidget(self.rawRespEdit)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rawRespLabel = QtGui.QLabel(self.tab)
        self.rawRespLabel.setObjectName("rawRespLabel")
        self.horizontalLayout_5.addWidget(self.rawRespLabel)
        self.searchEdit = QtGui.QLineEdit(self.tab)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout_5.addWidget(self.searchEdit)
        self.rawReBox = QtGui.QCheckBox(self.tab)
        self.rawReBox.setObjectName("rawReBox")
        self.horizontalLayout_5.addWidget(self.rawReBox)
        self.rawFindButton = QtGui.QPushButton(self.tab)
        self.rawFindButton.setObjectName("rawFindButton")
        self.horizontalLayout_5.addWidget(self.rawFindButton)
        self.rawFndLabel = QtGui.QLabel(self.tab)
        self.rawFndLabel.setText("")
        self.rawFndLabel.setObjectName("rawFndLabel")
        self.horizontalLayout_5.addWidget(self.rawFndLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.confirmedBox = QtGui.QCheckBox(self.tab)
        self.confirmedBox.setObjectName("confirmedBox")
        self.horizontalLayout_3.addWidget(self.confirmedBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.viewTab.addTab(self.tab, "")
        self.scriptsTab = QtGui.QWidget()
        self.scriptsTab.setObjectName("scriptsTab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scriptsTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scriptsEdit = Qsci.QsciScintilla(self.scriptsTab)
        self.scriptsEdit.setToolTip("")
        self.scriptsEdit.setWhatsThis("")
        self.scriptsEdit.setObjectName("scriptsEdit")
        self.verticalLayout_5.addWidget(self.scriptsEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrSearchLabel = QtGui.QLabel(self.scriptsTab)
        self.scrSearchLabel.setObjectName("scrSearchLabel")
        self.horizontalLayout.addWidget(self.scrSearchLabel)
        self.scrSearchEdit = QtGui.QLineEdit(self.scriptsTab)
        self.scrSearchEdit.setObjectName("scrSearchEdit")
        self.horizontalLayout.addWidget(self.scrSearchEdit)
        self.scriptsReBox = QtGui.QCheckBox(self.scriptsTab)
        self.scriptsReBox.setObjectName("scriptsReBox")
        self.horizontalLayout.addWidget(self.scriptsReBox)
        self.scriptsFindButton = QtGui.QPushButton(self.scriptsTab)
        self.scriptsFindButton.setObjectName("scriptsFindButton")
        self.horizontalLayout.addWidget(self.scriptsFindButton)
        self.scrFndLabel = QtGui.QLabel(self.scriptsTab)
        self.scrFndLabel.setText("")
        self.scrFndLabel.setObjectName("scrFndLabel")
        self.horizontalLayout.addWidget(self.scrFndLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.viewTab.addTab(self.scriptsTab, "")
        self.commentsTab = QtGui.QWidget()
        self.commentsTab.setObjectName("commentsTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.commentsTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comEdit = Qsci.QsciScintilla(self.commentsTab)
        self.comEdit.setToolTip("")
        self.comEdit.setWhatsThis("")
        self.comEdit.setObjectName("comEdit")
        self.verticalLayout_6.addWidget(self.comEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comSearchLabel = QtGui.QLabel(self.commentsTab)
        self.comSearchLabel.setObjectName("comSearchLabel")
        self.horizontalLayout_2.addWidget(self.comSearchLabel)
        self.comSearchEdit = QtGui.QLineEdit(self.commentsTab)
        self.comSearchEdit.setObjectName("comSearchEdit")
        self.horizontalLayout_2.addWidget(self.comSearchEdit)
        self.comReBox = QtGui.QCheckBox(self.commentsTab)
        self.comReBox.setObjectName("comReBox")
        self.horizontalLayout_2.addWidget(self.comReBox)
        self.comFindButton = QtGui.QPushButton(self.commentsTab)
        self.comFindButton.setObjectName("comFindButton")
        self.horizontalLayout_2.addWidget(self.comFindButton)
        self.comFndLabel = QtGui.QLabel(self.commentsTab)
        self.comFndLabel.setText("")
        self.comFndLabel.setObjectName("comFndLabel")
        self.horizontalLayout_2.addWidget(self.comFndLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.viewTab.addTab(self.commentsTab, "")
        self.renderTab = QtGui.QWidget()
        self.renderTab.setObjectName("renderTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.renderTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.renderEdit = QtGui.QTextEdit(self.renderTab)
        self.renderEdit.setObjectName("renderEdit")
        self.verticalLayout_3.addWidget(self.renderEdit)
        self.viewTab.addTab(self.renderTab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.notesEdit = QtGui.QTextEdit(self.tab_2)
        self.notesEdit.setObjectName("notesEdit")
        self.verticalLayout_7.addWidget(self.notesEdit)
        self.viewTab.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.splitter_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.updateButton = QtGui.QPushButton(self.centralwidget)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_4.addWidget(self.updateButton)
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout_4.addWidget(self.quitButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.viewTab.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.quitButton, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CrowsNest - Assessment Data Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.createButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Create a new database file", None, QtGui.QApplication.UnicodeUTF8))
        self.createButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a database file", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.diffButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Diff Responses", None, QtGui.QApplication.UnicodeUTF8))
        self.diffButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTree.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Confirmed", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTree.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTree.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "HTTP Status", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTree.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Request Data", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTree.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "Content Length", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTree.headerItem().setText(6, QtGui.QApplication.translate("MainWindow", "Request Time", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTab.setTabText(self.viewTab.indexOf(self.rawTab), QtGui.QApplication.translate("MainWindow", "Request", None, QtGui.QApplication.UnicodeUTF8))
        self.rawRespLabel.setText(QtGui.QApplication.translate("MainWindow", "Search: ", None, QtGui.QApplication.UnicodeUTF8))
        self.searchEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Search through the current Raw Response", None, QtGui.QApplication.UnicodeUTF8))
        self.rawReBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Use Regular Expression Syntax", None, QtGui.QApplication.UnicodeUTF8))
        self.rawReBox.setText(QtGui.QApplication.translate("MainWindow", "RE", None, QtGui.QApplication.UnicodeUTF8))
        self.rawFindButton.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.confirmedBox.setText(QtGui.QApplication.translate("MainWindow", "Confirmed", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTab.setTabText(self.viewTab.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Raw Response", None, QtGui.QApplication.UnicodeUTF8))
        self.scrSearchLabel.setText(QtGui.QApplication.translate("MainWindow", "Search: ", None, QtGui.QApplication.UnicodeUTF8))
        self.scriptsReBox.setText(QtGui.QApplication.translate("MainWindow", "RE", None, QtGui.QApplication.UnicodeUTF8))
        self.scriptsFindButton.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTab.setTabText(self.viewTab.indexOf(self.scriptsTab), QtGui.QApplication.translate("MainWindow", "Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.comSearchLabel.setText(QtGui.QApplication.translate("MainWindow", "Search: ", None, QtGui.QApplication.UnicodeUTF8))
        self.comReBox.setText(QtGui.QApplication.translate("MainWindow", "RE", None, QtGui.QApplication.UnicodeUTF8))
        self.comFindButton.setText(QtGui.QApplication.translate("MainWindow", "FInd", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTab.setTabText(self.viewTab.indexOf(self.commentsTab), QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTab.setTabText(self.viewTab.indexOf(self.renderTab), QtGui.QApplication.translate("MainWindow", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.viewTab.setTabText(self.viewTab.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qsci
