# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchDialog.ui'
#
# Created: Thu Jul  7 15:25:34 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SearchDialog(object):
    def setupUi(self, SearchDialog):
        SearchDialog.setObjectName(_fromUtf8("SearchDialog"))
        SearchDialog.resize(730, 539)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SearchDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(SearchDialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.searchText = QtGui.QLineEdit(self.frame_2)
        self.searchText.setObjectName(_fromUtf8("searchText"))
        self.verticalLayout_3.addWidget(self.searchText)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.searchPushButton = QtGui.QPushButton(self.frame_2)
        self.searchPushButton.setObjectName(_fromUtf8("searchPushButton"))
        self.horizontalLayout_2.addWidget(self.searchPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.cbCaseSensitive = QtGui.QCheckBox(self.frame_3)
        self.cbCaseSensitive.setObjectName(_fromUtf8("cbCaseSensitive"))
        self.verticalLayout_4.addWidget(self.cbCaseSensitive)
        self.cbWildcard = QtGui.QCheckBox(self.frame_3)
        self.cbWildcard.setObjectName(_fromUtf8("cbWildcard"))
        self.verticalLayout_4.addWidget(self.cbWildcard)
        self.cbRegularExpression = QtGui.QCheckBox(self.frame_3)
        self.cbRegularExpression.setObjectName(_fromUtf8("cbRegularExpression"))
        self.verticalLayout_4.addWidget(self.cbRegularExpression)
        self.cbInvertSearch = QtGui.QCheckBox(self.frame_3)
        self.cbInvertSearch.setObjectName(_fromUtf8("cbInvertSearch"))
        self.verticalLayout_4.addWidget(self.cbInvertSearch)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cbRequestHeaders = QtGui.QCheckBox(self.frame_4)
        self.cbRequestHeaders.setChecked(True)
        self.cbRequestHeaders.setObjectName(_fromUtf8("cbRequestHeaders"))
        self.gridLayout_2.addWidget(self.cbRequestHeaders, 1, 0, 1, 1)
        self.cbRequestBody = QtGui.QCheckBox(self.frame_4)
        self.cbRequestBody.setChecked(True)
        self.cbRequestBody.setObjectName(_fromUtf8("cbRequestBody"))
        self.gridLayout_2.addWidget(self.cbRequestBody, 2, 0, 1, 1)
        self.cbResponseHeaders = QtGui.QCheckBox(self.frame_4)
        self.cbResponseHeaders.setChecked(True)
        self.cbResponseHeaders.setObjectName(_fromUtf8("cbResponseHeaders"))
        self.gridLayout_2.addWidget(self.cbResponseHeaders, 3, 0, 1, 1)
        self.cbResponseBody = QtGui.QCheckBox(self.frame_4)
        self.cbResponseBody.setChecked(True)
        self.cbResponseBody.setObjectName(_fromUtf8("cbResponseBody"))
        self.gridLayout_2.addWidget(self.cbResponseBody, 4, 0, 1, 1)
        self.cbRequestUrl = QtGui.QCheckBox(self.frame_4)
        self.cbRequestUrl.setObjectName(_fromUtf8("cbRequestUrl"))
        self.gridLayout_2.addWidget(self.cbRequestUrl, 1, 1, 1, 1)
        self.cbAnalystNotes = QtGui.QCheckBox(self.frame_4)
        self.cbAnalystNotes.setObjectName(_fromUtf8("cbAnalystNotes"))
        self.gridLayout_2.addWidget(self.cbAnalystNotes, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.splitter_4 = QtGui.QSplitter(SearchDialog)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.searchResultsTree = QtGui.QTreeView(self.splitter_4)
        self.searchResultsTree.setObjectName(_fromUtf8("searchResultsTree"))
        self.searchTabWidget = QtGui.QTabWidget(self.splitter_4)
        self.searchTabWidget.setObjectName(_fromUtf8("searchTabWidget"))
        self.verticalLayout_2.addWidget(self.splitter_4)
        self.searchSearchControlPlaceholder = QtGui.QWidget(SearchDialog)
        self.searchSearchControlPlaceholder.setObjectName(_fromUtf8("searchSearchControlPlaceholder"))
        self.verticalLayout_2.addWidget(self.searchSearchControlPlaceholder)

        self.retranslateUi(SearchDialog)
        self.searchTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(SearchDialog)

    def retranslateUi(self, SearchDialog):
        SearchDialog.setWindowTitle(QtGui.QApplication.translate("SearchDialog", "Search Dialog", None, QtGui.QApplication.UnicodeUTF8))
        SearchDialog.setToolTip(QtGui.QApplication.translate("SearchDialog", "Search Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SearchDialog", "Search Text", None, QtGui.QApplication.UnicodeUTF8))
        self.searchPushButton.setText(QtGui.QApplication.translate("SearchDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SearchDialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cbCaseSensitive.setText(QtGui.QApplication.translate("SearchDialog", "Case Sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.cbWildcard.setText(QtGui.QApplication.translate("SearchDialog", "Wildcard", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRegularExpression.setText(QtGui.QApplication.translate("SearchDialog", "Regular Expression", None, QtGui.QApplication.UnicodeUTF8))
        self.cbInvertSearch.setText(QtGui.QApplication.translate("SearchDialog", "Invert Search", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRequestHeaders.setText(QtGui.QApplication.translate("SearchDialog", "Request Headers", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRequestBody.setText(QtGui.QApplication.translate("SearchDialog", "Request Body", None, QtGui.QApplication.UnicodeUTF8))
        self.cbResponseHeaders.setText(QtGui.QApplication.translate("SearchDialog", "Response Headers", None, QtGui.QApplication.UnicodeUTF8))
        self.cbResponseBody.setText(QtGui.QApplication.translate("SearchDialog", "Response Body", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRequestUrl.setText(QtGui.QApplication.translate("SearchDialog", "Request URL", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAnalystNotes.setText(QtGui.QApplication.translate("SearchDialog", "Analyst Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SearchDialog", "Search Locations", None, QtGui.QApplication.UnicodeUTF8))

