# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SequenceDialog.ui'
#
# Created: Tue Aug  2 11:42:59 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_seqBuildDialog(object):
    def setupUi(self, seqBuildDialog):
        seqBuildDialog.setObjectName(_fromUtf8("seqBuildDialog"))
        seqBuildDialog.resize(972, 611)
        self.verticalLayout = QtGui.QVBoxLayout(seqBuildDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sequenceTabWidget = QtGui.QTabWidget(seqBuildDialog)
        self.sequenceTabWidget.setEnabled(True)
        self.sequenceTabWidget.setObjectName(_fromUtf8("sequenceTabWidget"))
        self.tabSequence = QtGui.QWidget()
        self.tabSequence.setObjectName(_fromUtf8("tabSequence"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSequence)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(self.tabSequence)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sequencesComboBox = QtGui.QComboBox(self.frame)
        self.sequencesComboBox.setEditable(True)
        self.sequencesComboBox.setObjectName(_fromUtf8("sequencesComboBox"))
        self.sequencesComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.sequencesComboBox)
        self.startRecordingButton = QtGui.QPushButton(self.frame)
        self.startRecordingButton.setObjectName(_fromUtf8("startRecordingButton"))
        self.horizontalLayout.addWidget(self.startRecordingButton)
        self.stopRecordingButton = QtGui.QPushButton(self.frame)
        self.stopRecordingButton.setEnabled(False)
        self.stopRecordingButton.setObjectName(_fromUtf8("stopRecordingButton"))
        self.horizontalLayout.addWidget(self.stopRecordingButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.saveSequenceButton = QtGui.QPushButton(self.frame)
        self.saveSequenceButton.setObjectName(_fromUtf8("saveSequenceButton"))
        self.horizontalLayout.addWidget(self.saveSequenceButton)
        self.deleteSequenceButton = QtGui.QPushButton(self.frame)
        self.deleteSequenceButton.setObjectName(_fromUtf8("deleteSequenceButton"))
        self.horizontalLayout.addWidget(self.deleteSequenceButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.sequenceStepsTreeWidget = QtGui.QTreeWidget(self.frame)
        self.sequenceStepsTreeWidget.setAutoFillBackground(False)
        self.sequenceStepsTreeWidget.setAlternatingRowColors(True)
        self.sequenceStepsTreeWidget.setObjectName(_fromUtf8("sequenceStepsTreeWidget"))
        self.verticalLayout_5.addWidget(self.sequenceStepsTreeWidget)
        self.sequencePropertiesTabWidget = QtGui.QTabWidget(self.splitter)
        self.sequencePropertiesTabWidget.setObjectName(_fromUtf8("sequencePropertiesTabWidget"))
        self.propertiesTabWidget = QtGui.QWidget()
        self.propertiesTabWidget.setObjectName(_fromUtf8("propertiesTabWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.propertiesTabWidget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.propertiesTabWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.sequenceTypeComboBox = QtGui.QComboBox(self.propertiesTabWidget)
        self.sequenceTypeComboBox.setObjectName(_fromUtf8("sequenceTypeComboBox"))
        self.sequenceTypeComboBox.addItem(_fromUtf8(""))
        self.sequenceTypeComboBox.setItemText(0, _fromUtf8(""))
        self.sequenceTypeComboBox.addItem(_fromUtf8(""))
        self.sequenceTypeComboBox.addItem(_fromUtf8(""))
        self.sequenceTypeComboBox.addItem(_fromUtf8(""))
        self.sequenceTypeComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.sequenceTypeComboBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.useSessionDetectionCheckbox = QtGui.QCheckBox(self.propertiesTabWidget)
        self.useSessionDetectionCheckbox.setObjectName(_fromUtf8("useSessionDetectionCheckbox"))
        self.horizontalLayout_7.addWidget(self.useSessionDetectionCheckbox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.includeMediaCheckbox = QtGui.QCheckBox(self.propertiesTabWidget)
        self.includeMediaCheckbox.setObjectName(_fromUtf8("includeMediaCheckbox"))
        self.horizontalLayout_9.addWidget(self.includeMediaCheckbox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.dynamicDataCheckbox = QtGui.QCheckBox(self.propertiesTabWidget)
        self.dynamicDataCheckbox.setObjectName(_fromUtf8("dynamicDataCheckbox"))
        self.horizontalLayout_6.addWidget(self.dynamicDataCheckbox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.useBrowserCheckbox = QtGui.QCheckBox(self.propertiesTabWidget)
        self.useBrowserCheckbox.setObjectName(_fromUtf8("useBrowserCheckbox"))
        self.horizontalLayout_10.addWidget(self.useBrowserCheckbox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.sequencePropertiesTabWidget.addTab(self.propertiesTabWidget, _fromUtf8(""))
        self.requestViewSequenceTabWidget = QtGui.QWidget()
        self.requestViewSequenceTabWidget.setObjectName(_fromUtf8("requestViewSequenceTabWidget"))
        self.sequencePropertiesTabWidget.addTab(self.requestViewSequenceTabWidget, _fromUtf8(""))
        self.responseViewSequenceTabWidget = QtGui.QWidget()
        self.responseViewSequenceTabWidget.setObjectName(_fromUtf8("responseViewSequenceTabWidget"))
        self.sequencePropertiesTabWidget.addTab(self.responseViewSequenceTabWidget, _fromUtf8(""))
        self.renderViewSequenceTabWidget = QtGui.QWidget()
        self.renderViewSequenceTabWidget.setObjectName(_fromUtf8("renderViewSequenceTabWidget"))
        self.sequencePropertiesTabWidget.addTab(self.renderViewSequenceTabWidget, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.splitter)
        self.frame_2 = QtGui.QFrame(self.tabSequence)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.inSessionPatternEdit = QtGui.QLineEdit(self.frame_2)
        self.inSessionPatternEdit.setObjectName(_fromUtf8("inSessionPatternEdit"))
        self.horizontalLayout_3.addWidget(self.inSessionPatternEdit)
        self.inSessionPatternRE = QtGui.QCheckBox(self.frame_2)
        self.inSessionPatternRE.setObjectName(_fromUtf8("inSessionPatternRE"))
        self.horizontalLayout_3.addWidget(self.inSessionPatternRE)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.outOfSessionPatternEdit = QtGui.QLineEdit(self.frame_2)
        self.outOfSessionPatternEdit.setObjectName(_fromUtf8("outOfSessionPatternEdit"))
        self.horizontalLayout_5.addWidget(self.outOfSessionPatternEdit)
        self.outOfSessionPatternRE = QtGui.QCheckBox(self.frame_2)
        self.outOfSessionPatternRE.setObjectName(_fromUtf8("outOfSessionPatternRE"))
        self.horizontalLayout_5.addWidget(self.outOfSessionPatternRE)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.sequenceTabWidget.addTab(self.tabSequence, _fromUtf8(""))
        self.tabWebBrowser = QtGui.QWidget()
        self.tabWebBrowser.setObjectName(_fromUtf8("tabWebBrowser"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabWebBrowser)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.webBrowserFrame = QtGui.QFrame(self.tabWebBrowser)
        self.webBrowserFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.webBrowserFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.webBrowserFrame.setObjectName(_fromUtf8("webBrowserFrame"))
        self.verticalLayout_2.addWidget(self.webBrowserFrame)
        self.sequenceTabWidget.addTab(self.tabWebBrowser, _fromUtf8(""))
        self.sequenceBuilderCookiesTab = QtGui.QWidget()
        self.sequenceBuilderCookiesTab.setObjectName(_fromUtf8("sequenceBuilderCookiesTab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.sequenceBuilderCookiesTab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.sequenceCookiesTreeWidget = QtGui.QTreeWidget(self.sequenceBuilderCookiesTab)
        self.sequenceCookiesTreeWidget.setAlternatingRowColors(True)
        self.sequenceCookiesTreeWidget.setObjectName(_fromUtf8("sequenceCookiesTreeWidget"))
        self.verticalLayout_4.addWidget(self.sequenceCookiesTreeWidget)
        self.sequenceTabWidget.addTab(self.sequenceBuilderCookiesTab, _fromUtf8(""))
        self.sequenceBuilderParameters = QtGui.QWidget()
        self.sequenceBuilderParameters.setObjectName(_fromUtf8("sequenceBuilderParameters"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.sequenceBuilderParameters)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.sequenceParametersTreeWidget = QtGui.QTreeWidget(self.sequenceBuilderParameters)
        self.sequenceParametersTreeWidget.setObjectName(_fromUtf8("sequenceParametersTreeWidget"))
        self.verticalLayout_6.addWidget(self.sequenceParametersTreeWidget)
        self.sequenceTabWidget.addTab(self.sequenceBuilderParameters, _fromUtf8(""))
        self.verticalLayout.addWidget(self.sequenceTabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.seqCloseButton = QtGui.QPushButton(seqBuildDialog)
        self.seqCloseButton.setObjectName(_fromUtf8("seqCloseButton"))
        self.horizontalLayout_2.addWidget(self.seqCloseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(seqBuildDialog)
        self.sequenceTabWidget.setCurrentIndex(0)
        self.sequencePropertiesTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.seqCloseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), seqBuildDialog.close)
        QtCore.QMetaObject.connectSlotsByName(seqBuildDialog)

    def retranslateUi(self, seqBuildDialog):
        seqBuildDialog.setWindowTitle(QtGui.QApplication.translate("seqBuildDialog", "Sequence Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencesComboBox.setItemText(0, QtGui.QApplication.translate("seqBuildDialog", "Untitled Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.startRecordingButton.setText(QtGui.QApplication.translate("seqBuildDialog", "Start Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.stopRecordingButton.setText(QtGui.QApplication.translate("seqBuildDialog", "Stop Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSequenceButton.setText(QtGui.QApplication.translate("seqBuildDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSequenceButton.setText(QtGui.QApplication.translate("seqBuildDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceStepsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("seqBuildDialog", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceStepsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("seqBuildDialog", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceStepsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("seqBuildDialog", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceStepsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("seqBuildDialog", "Content Type", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceStepsTreeWidget.headerItem().setText(4, QtGui.QApplication.translate("seqBuildDialog", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("seqBuildDialog", "Sequence Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTypeComboBox.setItemText(1, QtGui.QApplication.translate("seqBuildDialog", "Sign In", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTypeComboBox.setItemText(2, QtGui.QApplication.translate("seqBuildDialog", "Sign Out", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTypeComboBox.setItemText(3, QtGui.QApplication.translate("seqBuildDialog", "Fuzz", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTypeComboBox.setItemText(4, QtGui.QApplication.translate("seqBuildDialog", "Generic", None, QtGui.QApplication.UnicodeUTF8))
        self.useSessionDetectionCheckbox.setText(QtGui.QApplication.translate("seqBuildDialog", "Use session detection?", None, QtGui.QApplication.UnicodeUTF8))
        self.includeMediaCheckbox.setText(QtGui.QApplication.translate("seqBuildDialog", "Include media responses in sequence?", None, QtGui.QApplication.UnicodeUTF8))
        self.dynamicDataCheckbox.setText(QtGui.QApplication.translate("seqBuildDialog", "Dynamic data replacement?", None, QtGui.QApplication.UnicodeUTF8))
        self.useBrowserCheckbox.setText(QtGui.QApplication.translate("seqBuildDialog", "Run sequence in browser instance?", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencePropertiesTabWidget.setTabText(self.sequencePropertiesTabWidget.indexOf(self.propertiesTabWidget), QtGui.QApplication.translate("seqBuildDialog", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencePropertiesTabWidget.setTabText(self.sequencePropertiesTabWidget.indexOf(self.requestViewSequenceTabWidget), QtGui.QApplication.translate("seqBuildDialog", "Request", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencePropertiesTabWidget.setTabText(self.sequencePropertiesTabWidget.indexOf(self.responseViewSequenceTabWidget), QtGui.QApplication.translate("seqBuildDialog", "Response", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencePropertiesTabWidget.setTabText(self.sequencePropertiesTabWidget.indexOf(self.renderViewSequenceTabWidget), QtGui.QApplication.translate("seqBuildDialog", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("seqBuildDialog", "In-Session Pattern:", None, QtGui.QApplication.UnicodeUTF8))
        self.inSessionPatternRE.setText(QtGui.QApplication.translate("seqBuildDialog", "RE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("seqBuildDialog", "Out-of-Session Pattern:", None, QtGui.QApplication.UnicodeUTF8))
        self.outOfSessionPatternRE.setText(QtGui.QApplication.translate("seqBuildDialog", "RE", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTabWidget.setTabText(self.sequenceTabWidget.indexOf(self.tabSequence), QtGui.QApplication.translate("seqBuildDialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTabWidget.setTabText(self.sequenceTabWidget.indexOf(self.tabWebBrowser), QtGui.QApplication.translate("seqBuildDialog", "Web Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("seqBuildDialog", "Track?", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("seqBuildDialog", "Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("seqBuildDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("seqBuildDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(4, QtGui.QApplication.translate("seqBuildDialog", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(5, QtGui.QApplication.translate("seqBuildDialog", "Expiry", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(6, QtGui.QApplication.translate("seqBuildDialog", "Session Cookie", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(7, QtGui.QApplication.translate("seqBuildDialog", "HttpOnly", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceCookiesTreeWidget.headerItem().setText(8, QtGui.QApplication.translate("seqBuildDialog", "Secure", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTabWidget.setTabText(self.sequenceTabWidget.indexOf(self.sequenceBuilderCookiesTab), QtGui.QApplication.translate("seqBuildDialog", "Cookies", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("seqBuildDialog", "Track", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("seqBuildDialog", "ID#", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("seqBuildDialog", "XREF", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("seqBuildDialog", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(4, QtGui.QApplication.translate("seqBuildDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(5, QtGui.QApplication.translate("seqBuildDialog", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(6, QtGui.QApplication.translate("seqBuildDialog", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(7, QtGui.QApplication.translate("seqBuildDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(8, QtGui.QApplication.translate("seqBuildDialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceParametersTreeWidget.headerItem().setText(9, QtGui.QApplication.translate("seqBuildDialog", "URL(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceTabWidget.setTabText(self.sequenceTabWidget.indexOf(self.sequenceBuilderParameters), QtGui.QApplication.translate("seqBuildDialog", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.seqCloseButton.setText(QtGui.QApplication.translate("seqBuildDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

